apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::098139964440:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-ORD5YIU1T2CR
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::098139964440:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-28T09:49:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1634"
  uid: a8a4ac35-f6ec-47aa-836e-8c2f1e399574
